### PR TITLE
Add Support for Linux arm64 Builds

### PR DESCRIPTION
**Pull request by priyagupta108**
This Pull Request introduces changes to enable building of Python packages for Linux arm64 architecture.

### CODE REVIEW

**Comment by mayeut** [comment]
This PR closes #230

That being said, neither pull requests fix the issue.
Either you need to be cross building on x86_64 which would require much more changes to the builder script or you need to build on an aarch64 runner (you might have access through the private beta but as everything is private, I don't even know what's provided).
In order to test, again, you either need an aarch64 runner or update the tests scripts to run with qemu on an x86_64 runner.

**Review by mayeut — CHANGES_REQUESTED** [review]
This PR closes https://github.com/actions/python-versions/pull/230

That being said, neither pull requests fix the issue.
Either you need to be cross building on x86_64 which would require much more changes to the builder script or you need to build on an aarch64 runner (you might have access through the private beta but as everything is private, I don't even know what's provided).
In order to test, again, you either need an aarch64 runner or update the tests scripts to run with qemu on an x86_64 runner.

**Comment by mayeut** [comment]
> Should have been Q1 2024, but we don't seem to be there yet

It's should be a **private** BETA for now so not everyone can use/see that - I know I don't - (or is it not ready ?).

At least, it seems they now do have access to some ubuntu 22.04 aarch64 runners: https://github.com/actions/python-versions/actions/runs/9254745717

**Comment by dimaqq** [comment]
I got an email from GitHub about this, but IIRC arm64 builders have only been enabled for organisations and not individuals?

I’ll try to validate this.

**Review by dimaqq — APPROVED** [review]
The change looks good to me, though admittedly I didn't run it myself.

**Review by mahabaleshwars — APPROVED** [review]

**Review by priya-kinthali — APPROVED** [review]

**Comment by atwoodjw** [comment]
I still get the following.

```
Error: The version '3.11' with architecture 'arm64' was not found for Ubuntu 22.04.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
  ```
  
And sure enough, I still only see ARM builds for Darwin in versions-manifest.json.

Is there additional work required to use these changes and build for ubuntu/arm64?

**Comment by atwoodjw** [comment]
Ah, it looks like https://github.com/actions/python-versions/pull/289 will resolve.

**Pull request merged**
