### PR TITLE
There is no AGENT_TOOLSDIRECTORY on GitHub images

### PR DESCRIPTION
**Pull request by mjpieters**
This change reflects what the Windows installer already does:  https://github.com/mjpieters/python-versions/blob/c0e7ef2c3c5b8e3dce50c0caceaafb4a5266a36c/installers/win-setup-template.ps1#L82-L87

### CODE REVIEW

**Comment by mjpieters** [comment]
Incidentally: the [`setup-python` README](https://github.com/actions/setup-python/blob/master/README.md#available-versions-of-python) tells us to open issues here in the `python-versions` repository to request new Python releases:

> - If there is a specific version of Python that is not available, you can open an issue in the `python-versions` repository.

Yet this repository doesn’t have the issues option enabled. Oversight perhaps?

**Comment by konradpabjan** [comment]
Hello @mjpieters 

Apologies for the `README` discrepancies (I've updated it now). I forgot to update that section, when i removed some other [references](https://github.com/actions/setup-python/commit/8910d815ad06a00ae0c3e0e810acd611ea5e4dde#diff-04c6e90faac2675aa89e2176d2eec7d8) to creating issues in this repository.

The reason issues are closed in this repo is so that it is easier to maintain and triage. Python issues come in `setup-python` and `virtual-environments` so having a third repository to regularly check on would become difficult

**Comment by konradpabjan** [comment]
@maxim-lobanov, @MaksimZhukov could you take a look at this small code change?

**Comment by maxim-lobanov** [comment]
Hello @mjpieters, your changes LGTM. We didn't do these changes initially because Hosted Ubuntu images have `AGENT_TOOLSDIRECTORY` as far as I know. But your fix is important to support self-hosted agents properly.

Currently, CI fails on your changes because of the way that we use to generate installer scripts. I have improved it in scope of #22 . Could you please pull latest master to your branch and I will rerun CI?

**Comment by mjpieters** [comment]
@MaksimZhukov I rebased and force-pushed, I suspect that now means you have to run the pipeline manually. GitHub doesn't think there is a need for any checks, at any rate.

Let's see if I have permission to trigger a run:

/azp run

**Comment by maxim-lobanov** [comment]
looks like azp run doesn't run build properly :(
I have run checks manually: https://github.visualstudio.com/virtual-environments/_build/results?buildId=67728&view=logs&j=a851cb31-2814-50bb-6af1-fa649763ba71&t=f0eef93c-9563-5abf-9747-41cd68506a2a

**Comment by mjpieters** [comment]
Looks like the manual build completed successfully.

**Comment by maxim-lobanov** [comment]
@mjpieters  , merged. I will re-upload existing versions with this fix.

**Comment by maxim-lobanov** [comment]
All versions were regenerated and re-uploaded with this fix

**Pull request merged**
